/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AstroRouteImport } from './routes/astro'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TirageIndexRouteImport } from './routes/tirage/index'
import { Route as ArcanesIndexRouteImport } from './routes/arcanes/index'
import { Route as TirageSpreadRouteImport } from './routes/tirage/$spread'
import { Route as ArcanesSuitRouteImport } from './routes/arcanes/$suit'

const AstroRoute = AstroRouteImport.update({
  id: '/astro',
  path: '/astro',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TirageIndexRoute = TirageIndexRouteImport.update({
  id: '/tirage/',
  path: '/tirage/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcanesIndexRoute = ArcanesIndexRouteImport.update({
  id: '/arcanes/',
  path: '/arcanes/',
  getParentRoute: () => rootRouteImport,
} as any)
const TirageSpreadRoute = TirageSpreadRouteImport.update({
  id: '/tirage/$spread',
  path: '/tirage/$spread',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcanesSuitRoute = ArcanesSuitRouteImport.update({
  id: '/arcanes/$suit',
  path: '/arcanes/$suit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/astro': typeof AstroRoute
  '/arcanes/$suit': typeof ArcanesSuitRoute
  '/tirage/$spread': typeof TirageSpreadRoute
  '/arcanes/': typeof ArcanesIndexRoute
  '/tirage/': typeof TirageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/astro': typeof AstroRoute
  '/arcanes/$suit': typeof ArcanesSuitRoute
  '/tirage/$spread': typeof TirageSpreadRoute
  '/arcanes': typeof ArcanesIndexRoute
  '/tirage': typeof TirageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/astro': typeof AstroRoute
  '/arcanes/$suit': typeof ArcanesSuitRoute
  '/tirage/$spread': typeof TirageSpreadRoute
  '/arcanes/': typeof ArcanesIndexRoute
  '/tirage/': typeof TirageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/astro'
    | '/arcanes/$suit'
    | '/tirage/$spread'
    | '/arcanes/'
    | '/tirage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/astro'
    | '/arcanes/$suit'
    | '/tirage/$spread'
    | '/arcanes'
    | '/tirage'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/astro'
    | '/arcanes/$suit'
    | '/tirage/$spread'
    | '/arcanes/'
    | '/tirage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AstroRoute: typeof AstroRoute
  ArcanesSuitRoute: typeof ArcanesSuitRoute
  TirageSpreadRoute: typeof TirageSpreadRoute
  ArcanesIndexRoute: typeof ArcanesIndexRoute
  TirageIndexRoute: typeof TirageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/astro': {
      id: '/astro'
      path: '/astro'
      fullPath: '/astro'
      preLoaderRoute: typeof AstroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tirage/': {
      id: '/tirage/'
      path: '/tirage'
      fullPath: '/tirage/'
      preLoaderRoute: typeof TirageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcanes/': {
      id: '/arcanes/'
      path: '/arcanes'
      fullPath: '/arcanes/'
      preLoaderRoute: typeof ArcanesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tirage/$spread': {
      id: '/tirage/$spread'
      path: '/tirage/$spread'
      fullPath: '/tirage/$spread'
      preLoaderRoute: typeof TirageSpreadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcanes/$suit': {
      id: '/arcanes/$suit'
      path: '/arcanes/$suit'
      fullPath: '/arcanes/$suit'
      preLoaderRoute: typeof ArcanesSuitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AstroRoute: AstroRoute,
  ArcanesSuitRoute: ArcanesSuitRoute,
  TirageSpreadRoute: TirageSpreadRoute,
  ArcanesIndexRoute: ArcanesIndexRoute,
  TirageIndexRoute: TirageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
